/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutIndexRouteImport } from './routes/checkout/index'
import { Route as OnboardingTalkItOutRouteImport } from './routes/onboarding_.talk-it-out'
import { Route as OnboardingConversationalRouteImport } from './routes/onboarding_.conversational'
import { Route as CheckoutPaymentRouteImport } from './routes/checkout/payment'
import { Route as CheckoutDoneRouteImport } from './routes/checkout/done'

const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CheckoutRoute,
} as any)
const OnboardingTalkItOutRoute = OnboardingTalkItOutRouteImport.update({
  id: '/onboarding_/talk-it-out',
  path: '/onboarding/talk-it-out',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingConversationalRoute =
  OnboardingConversationalRouteImport.update({
    id: '/onboarding_/conversational',
    path: '/onboarding/conversational',
    getParentRoute: () => rootRouteImport,
  } as any)
const CheckoutPaymentRoute = CheckoutPaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => CheckoutRoute,
} as any)
const CheckoutDoneRoute = CheckoutDoneRouteImport.update({
  id: '/done',
  path: '/done',
  getParentRoute: () => CheckoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/community': typeof CommunityRoute
  '/faqs': typeof FaqsRoute
  '/onboarding': typeof OnboardingRoute
  '/products': typeof ProductsRoute
  '/checkout/done': typeof CheckoutDoneRoute
  '/checkout/payment': typeof CheckoutPaymentRoute
  '/onboarding/conversational': typeof OnboardingConversationalRoute
  '/onboarding/talk-it-out': typeof OnboardingTalkItOutRoute
  '/checkout/': typeof CheckoutIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/community': typeof CommunityRoute
  '/faqs': typeof FaqsRoute
  '/onboarding': typeof OnboardingRoute
  '/products': typeof ProductsRoute
  '/checkout/done': typeof CheckoutDoneRoute
  '/checkout/payment': typeof CheckoutPaymentRoute
  '/onboarding/conversational': typeof OnboardingConversationalRoute
  '/onboarding/talk-it-out': typeof OnboardingTalkItOutRoute
  '/checkout': typeof CheckoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/community': typeof CommunityRoute
  '/faqs': typeof FaqsRoute
  '/onboarding': typeof OnboardingRoute
  '/products': typeof ProductsRoute
  '/checkout/done': typeof CheckoutDoneRoute
  '/checkout/payment': typeof CheckoutPaymentRoute
  '/onboarding_/conversational': typeof OnboardingConversationalRoute
  '/onboarding_/talk-it-out': typeof OnboardingTalkItOutRoute
  '/checkout/': typeof CheckoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/checkout'
    | '/community'
    | '/faqs'
    | '/onboarding'
    | '/products'
    | '/checkout/done'
    | '/checkout/payment'
    | '/onboarding/conversational'
    | '/onboarding/talk-it-out'
    | '/checkout/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/community'
    | '/faqs'
    | '/onboarding'
    | '/products'
    | '/checkout/done'
    | '/checkout/payment'
    | '/onboarding/conversational'
    | '/onboarding/talk-it-out'
    | '/checkout'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/checkout'
    | '/community'
    | '/faqs'
    | '/onboarding'
    | '/products'
    | '/checkout/done'
    | '/checkout/payment'
    | '/onboarding_/conversational'
    | '/onboarding_/talk-it-out'
    | '/checkout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  CommunityRoute: typeof CommunityRoute
  FaqsRoute: typeof FaqsRoute
  OnboardingRoute: typeof OnboardingRoute
  ProductsRoute: typeof ProductsRoute
  OnboardingConversationalRoute: typeof OnboardingConversationalRoute
  OnboardingTalkItOutRoute: typeof OnboardingTalkItOutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/'
      fullPath: '/checkout/'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/onboarding_/talk-it-out': {
      id: '/onboarding_/talk-it-out'
      path: '/onboarding/talk-it-out'
      fullPath: '/onboarding/talk-it-out'
      preLoaderRoute: typeof OnboardingTalkItOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding_/conversational': {
      id: '/onboarding_/conversational'
      path: '/onboarding/conversational'
      fullPath: '/onboarding/conversational'
      preLoaderRoute: typeof OnboardingConversationalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/payment': {
      id: '/checkout/payment'
      path: '/payment'
      fullPath: '/checkout/payment'
      preLoaderRoute: typeof CheckoutPaymentRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/checkout/done': {
      id: '/checkout/done'
      path: '/done'
      fullPath: '/checkout/done'
      preLoaderRoute: typeof CheckoutDoneRouteImport
      parentRoute: typeof CheckoutRoute
    }
  }
}

interface CheckoutRouteChildren {
  CheckoutDoneRoute: typeof CheckoutDoneRoute
  CheckoutPaymentRoute: typeof CheckoutPaymentRoute
  CheckoutIndexRoute: typeof CheckoutIndexRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutDoneRoute: CheckoutDoneRoute,
  CheckoutPaymentRoute: CheckoutPaymentRoute,
  CheckoutIndexRoute: CheckoutIndexRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  CommunityRoute: CommunityRoute,
  FaqsRoute: FaqsRoute,
  OnboardingRoute: OnboardingRoute,
  ProductsRoute: ProductsRoute,
  OnboardingConversationalRoute: OnboardingConversationalRoute,
  OnboardingTalkItOutRoute: OnboardingTalkItOutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
